FROM gradle:8.14.3-jdk21

USER root
RUN apt-get update \
    && apt-get install -y --no-install-recommends curl \
    && rm -rf /var/lib/apt/lists/*

USER gradle
WORKDIR /workspace

EXPOSE 8080

CMD ["gradle", "--no-daemon", "--project-cache-dir", "/home/gradle/.gradle/dev-project-cache", "bootRun"]
