package com.adp.gateway.runtime.domain;

import java.time.OffsetDateTime;

public record RuntimeExecutionTrace(
    String executionId,
    String requestId,
    String traceId,
    String idempotencyKey,
    String workloadId,
    String purposeCode,
    String subjectRefDigest,
    String providerProfileId,
    String destinationProfileId,
    String destinationProfileVersion,
    String destinationProfileDigest,
    String destinationTenantId,
    String destinationRegion,
    String destinationRetentionPolicy,
    Boolean destinationTrainingUseAllowed,
    String institutionId,
    String approvalReference,
    String approvalVersion,
    String approvalScopeDigest,
    String approvalReuseStatus,
    String approvalReasonCodes,
    String policyLayers,
    String policyLayersDigest,
    String inputDigest,
    String canonicalContextDigest,
    String runtimeContextDigest,
    String policyVersion,
    String snapshotDigest,
    String decisionId,
    String finalAction,
    String transformExecutionId,
    String transformStatus,
    String transformOutputDigest,
    String outboundPayloadId,
    String outboundCandidateDigest,
    String outboundGuardStatus,
    String connectorExecutionId,
    String connectorStatus,
    String responseGuardStatus,
    String responseGuardReasonCodes,
    String requestedFields,
    String requestedFieldsDigest,
    Integer requestedFieldCount,
    String retrievedFields,
    String retrievedFieldsDigest,
    Integer retrievedFieldCount,
    String transformedFields,
    String transformedFieldsDigest,
    Integer transformedFieldCount,
    String releasedFields,
    String releasedFieldsDigest,
    Integer releasedFieldCount,
    String providerRequestId,
    String providerRequestDigest,
    String providerResponseDigest,
    String authorizationStatus,
    String status,
    OffsetDateTime createdAt,
    OffsetDateTime updatedAt
) {

    public static RuntimeExecutionTrace received(
        String executionId,
        String requestId,
        String traceId,
        String idempotencyKey,
        String workloadId,
        String purposeCode,
        String subjectRefDigest,
        String destinationProfileId,
        String institutionId,
        String approvalReference,
        String inputDigest,
        OffsetDateTime receivedAt
    ) {
        return new RuntimeExecutionTrace(
            executionId,
            requestId,
            traceId,
            idempotencyKey,
            workloadId,
            purposeCode,
            subjectRefDigest,
            null,
            destinationProfileId,
            null,
            null,
            null,
            null,
            null,
            null,
            institutionId,
            approvalReference,
            null,
            null,
            null,
            null,
            null,
            null,
            inputDigest,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            RuntimeExecutionStatus.RECEIVED.name(),
            receivedAt,
            receivedAt
        );
    }
}
