package com.adp.gateway.auth.domain;

public enum AdpRole {
    BUSINESS_OWNER,
    ANALYST,
    COMPLIANCE_REVIEWER,
    PRIVACY_REVIEWER,
    SECURITY_REVIEWER,
    DEVELOPER,
    OPERATOR,
    PRIVILEGED_OPERATOR,
    AUDITOR,
    RUNTIME_EXECUTOR
}
