package com.adp.gateway.common.error;

public enum ReasonCode {
    PROJECT_PROVISIONAL,
    PROJECT_PROVISIONAL_ALLOW,
    POLICY_ALLOW,
    POLICY_NOT_EVALUATED,
    POLICY_APPLICABLE,
    POLICY_NOT_APPLICABLE,
    POLICY_CONFLICT,
    POLICY_INCOMPLETE,
    RUNTIME_AUTHORIZATION_DENIED,
    MOCK_DECISION_ALLOW,
    VALIDATION_ERROR,
    MALFORMED_REQUEST,
    AUTHENTICATION_FAILED,
    AUTHORIZATION_DENIED,
    DATA_ACCESS_DENIED,
    IDEMPOTENCY_KEY_REUSED,
    IDEMPOTENCY_KEY_CONFLICT,
    IDEMPOTENCY_REQUEST_IN_PROGRESS,
    RUNTIME_EXECUTION_NOT_FOUND,
    DESTINATION_PROFILE_NOT_FOUND,
    APPROVAL_SCOPE_NOT_FOUND,
    EXECUTION_PACK_INPUT_REJECTED,
    OUTBOUND_GUARD_REJECTED,
    INTERNAL_ERROR
}
