package com.adp.gateway.common.error;

public enum ReasonCode {
    PROJECT_PROVISIONAL,
    MOCK_DECISION_ALLOW,
    VALIDATION_ERROR,
    MALFORMED_REQUEST,
    AUTHENTICATION_FAILED,
    AUTHORIZATION_DENIED,
    INTERNAL_ERROR
}
