package com.adp.gateway.common.error;

public enum ReasonCode {
    PROJECT_PROVISIONAL,
    PROJECT_PROVISIONAL_ALLOW,
    POLICY_ALLOW,
    POLICY_NOT_EVALUATED,
    POLICY_APPLICABLE,
    POLICY_NOT_APPLICABLE,
    POLICY_CONFLICT,
    POLICY_INCOMPLETE,
    RUNTIME_AUTHORIZATION_DENIED,
    MOCK_DECISION_ALLOW,
    VALIDATION_ERROR,
    MALFORMED_REQUEST,
    AUTHENTICATION_FAILED,
    AUTHORIZATION_DENIED,
    DATA_ACCESS_DENIED,
    IDEMPOTENCY_KEY_REUSED,
    RUNTIME_EXECUTION_NOT_FOUND,
    INTERNAL_ERROR
}
